DELETE http://localhost:3003/api/blogs/668be3a8a34d1b0cbaaa5836
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbGxhLm1hbGxpa2FzIiwiaWQiOiI2NjhiY2FmYmQ4MmJmZWM2YzNkODFkYjkiLCJpYXQiOjE3MjA0NDM4MDV9.dVY4BabCWgaj6MNla820I3EqmX_uk6TS3S1eVzZMocw